import ProductsPage from "../pages/ProductPage";
import HomePage from "../pages/HomePage";
import AboutPage from "../pages/AboutUs";
import NotFoundPage from "../pages/NotFoundPage";
import { dummyProducts } from "../stub/dummyReplace";

const PATHS = {
  home: {
    url: "/",
    component: HomePage,
  },
  products: {
    url: "/products",
    component: ProductsPage,
  },
  about: {
    url: "/about",
    component: AboutPage,
  },
} as const;

const defaultState = {
  products: dummyProducts,
  user: {
    image: "https://i.pravatar.cc/150?img=34",
    username: "dondada",
    firstName: "Skuba",
    lastName: "Koooper",
    id: 12345,
    email: "skub@mail.com",
    phone: "4121234567",
  },
};

/**
 * Handles routing logic for the application by matching the current path to a route definition.
 *
 * @param currentPath - The current URL path to match against the route definitions.
 * @param paths - An object containing route definitions, where each route has a `url` and a `component`.
 * @param state - The current application state to be passed to the route's component.
 * @returns The HTML string generated by the matched route's component, or the NotFoundPage if no match is found.
 */
export default async function router(
  currentPath = "",
  paths = PATHS,
  state = defaultState
): Promise<string> {
  // Find the matching route by path
  const currentRoute = Object.values(paths).find(
    (route) => route.url === currentPath
  );

  let html = await NotFoundPage();

  if (currentRoute) {
    html = await currentRoute.component(state);
  }

  return html;
}
